apiVersion: v1
kind: Service
metadata:
  name: rest-svc
  labels:
   name: restsample
   app: demo
spec:
   type: NodePort
   selector:
     name: restsample
     app: demo
   ports:
   - protocol: TCP
     port: 8099
     targetPort: 8099
     nodePort: 30199     
     